//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace expense_app
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction
    {
        public int Id { get; set; }
        public int userId { get; set; }
        public int Amount { get; set; }
        public string TransactionType { get; set; }
        public string Category { get; set; }
        public System.DateTime Date { get; set; }
        public string Description { get; set; }
        public byte[] Receipt { get; set; }
    
        public virtual User User { get; set; }
    }
}
